# Static DynBench Full_Warehouse scene for CrowdSim data collection.
prim_path: /World/Scene
z_offset: 0.0
scene_usd: /data/DynBench/isaacsim_scene/Full_Warehouse/full_warehouse.usd
scene_map: /data/DynBench/isaacsim_scene/Full_Warehouse/map/occupancy.yaml
static_obstacles: true
remove_prims: []
objects: {}
